name: Deploy Split Receipt v1
on:
 # push:
 #   branches: ["main"]
 #   tags:
 #    - "*"
  workflow_dispatch:
jobs:
  p-v1-job:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{secrets.PRIVATE_KEY}}" >> private_key
      - run: chmod 400 private_key
    # - run: eval `ssh-agent -s` && ssh-add private_key 
    # - run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key newfile.txt root@${{secrets.SERVER_IP}}:~/newfile.txt
      - run: echo $RANDOM | md5sum | head -c 20 > name.txt
      - run: echo "sh ~/runner_helper_sr $(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@${{secrets.SERVER_IP}}
    #  - run: ssh -o StrictHostKeyChecking=no -i private_key deploy@${{secrets.SERVER_IP}} "rm -rf ~/repo && . ~/runner_helper"
      - run: echo "cd ~/$(cat name.txt) && export PATH=/home/deploy/.nvm/versions/node/v14.17.5/bin:$PATH && git checkout v1 && yarn install && yarn build" | ssh -o StrictHostKeyChecking=no -i private_key deploy@${{secrets.SERVER_IP}}
      - run: echo "rm -rf /var/www/splitreceipt-v1 && cp -r ~/$(cat name.txt)/build /var/www/splitreceipt-v1" | ssh -o StrictHostKeyChecking=no -i private_key deploy@${{secrets.SERVER_IP}}
      - run: echo "rm -rf /etc/nginx/sites-enabled/sr-v1 && cp ~/$(cat name.txt)/v1-config /etc/nginx/sites-enabled/sr-v1 && sudo /usr/sbin/service nginx restart; rm -rf ~/$(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@${{secrets.SERVER_IP}}
      - run: eval `ssh-agent -s` && ssh-add -D
      - run: rm private_key
